---
# tasks file for ansible-role-docker-host

- name: Update system pacakge cache
  apt: update_cache=yes
  become: yes

- name: Install repository management packages
  apt:
    name: 
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common
    state: latest
    autoclean: yes

- name: Add Docker repository GPG key
  apt_key:
      url: https://download.docker.com/linux/debian/gpg
      id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
      state: present

- name: Add Docker repository
  apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_facts["distribution_release"] }} stable
      state: present
  notify: Update system package cache 

- name: Install Docker packages
  apt:
      name:
          - docker-ce 
          - docker-ce-cli 
          - containerd.io
          - docker-compose

- name: Enable and start Docker service
  systemd:
      name: docker
      state: started
      enabled: yes

- name: Create config directory
  file:
      path: /opt/services
      state: directory

- name: Copy docker-compose file
  template:
      src: '{{ docker_compose_template }}'
      dest: /opt/services/docker-compose.yml

- name: Create data directory
  file:
      path: '{{ service_data_dir }}'
      state: directory

- name: Copy other config files
  copy:
      src: '{{ docker_service_config_file_source }}'
      dest: '{{ docker_service_config_file_dest }}'

- name: Stop all docker services to prevent duplication
  command: docker-compose down
  args:
      chdir: /opt/services

- name: Start all docker services
  command: docker-compose up -d
  args:
      chdir: /opt/services
